version: 2

seeds:
  fraud_detection_using_dbt_and_snowpark:
    fct_swipe:
      +column_types:
        is_fraud: VARCHAR(1)
        swipe_id: INTEGER
        swipe_date: TIMESTAMP_NTZ
        swipe_amount: FLOAT
        mcc: VARCHAR(4)
        merchant_name: VARCHAR(100)
        merchant_zipcode: VARCHAR(5)
        policy_holder_id: INTEGER
        first_name: VARCHAR(50)
        last_name: VARCHAR(50)
        policy_start_date: TIMESTAMP_NTZ

